# Generated by Django 5.2.15 on 2026-06-06 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('traffic_density', models.FloatField()),
                ('horn_events_per_min', models.FloatField()),
                ('avg_speed', models.FloatField()),
                ('signal_wait_time', models.FloatField()),
                ('weather_condition', models.CharField(max_length=20)),
                ('road_quality_score', models.FloatField()),
                ('driver_experience_level', models.CharField(max_length=20)),
                ('stress_index', models.FloatField()),
                ('hour', models.IntegerField(blank=True, null=True)),
                ('day_of_week', models.IntegerField(blank=True, null=True)),
                ('is_weekend', models.BooleanField(default=False)),
                ('stress_level', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'traffic_record',
                'ordering': ['record_id'],
            },
        ),
    ]
