# Generated by Django 5.2.15 on 2026-06-06 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LIMELocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.IntegerField(unique=True)),
                ('lime_weights', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'xai_lime_local',
            },
        ),
        migrations.CreateModel(
            name='SHAPGlobal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feature', models.CharField(max_length=50)),
                ('shap_value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'xai_shap_global',
                'ordering': ['-shap_value'],
            },
        ),
        migrations.CreateModel(
            name='SHAPLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.IntegerField(unique=True)),
                ('shap_values', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'xai_shap_local',
            },
        ),
    ]
